### ISSUE TITLE
login failure (US) - indexerror in default.py

### ISSUE THREAD

**Issue by pleasantone** [liberty-developer/plugin.video.prime_instant#4]
Hi, I'm in the US, US account, us store configured.
Kodi 17.0 alpha via milhouse/librelec.

I deleted the keyboard scancodes, since they had confidential information.

```
20:32:54 523.081604 T:1961218048   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
20:38:48 877.022156 T:1471681440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.prime_instant-master/default.py", line 1282, in <module>
                                                index()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant-master/default.py", line 97, in index
                                                loginResult = login()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant-master/default.py", line 916, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
20:38:48 877.144348 T:1961218048   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
20:38:48 877.146973 T:1961218048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
20:39:33 921.702087 T:1463292832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.prime_instant-master/default.py", line 1229, in <module>
                                                login()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant-master/default.py", line 916, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
20:39:46 934.982117 T:1961218048   ERROR: Previous line repeats 1 times.
20:40:00 948.664307 T:1961218048  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"
20:40:00 948.665222 T:1961218048  NOTICE: Enabled debug logging due to GUI setting. Level 2.
20:40:30 978.817627 T:1961218048   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.prime_instant/)
20:40:30 978.817871 T:1961218048   DEBUG:   ParentPath = [plugin://plugin.video.prime_instant/]
20:40:30 978.820374 T:1764750240   DEBUG: Thread JobWorker start, auto delete: true
20:40:30 978.821594 T:1764750240   DEBUG: StartScript - calling plugin Amazon Prime Instant Video('plugin://plugin.video.prime_instant/','11','')
20:40:30 978.822327 T:1362629536   DEBUG: Thread LanguageInvoker start, auto delete: false
20:40:30 978.822754 T:1362629536    INFO: initializing python engine.
20:40:30 978.822876 T:1362629536   DEBUG: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.prime_instant-master/default.py): start processing
20:40:30 978.880066 T:1362629536   DEBUG: -->Python Interpreter Initialized<--
20:40:30 978.880371 T:1362629536   DEBUG: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.prime_instant-master/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.prime_instant-master/default.py"
20:40:30 978.881104 T:1362629536   DEBUG: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.prime_instant-master/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.prime_instant-master:/storage/.kodi/addons/script.module.mechanize/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
20:40:30 978.881226 T:1362629536   DEBUG: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.prime_instant-master/default.py): entering source directory /storage/.kodi/addons/plugin.video.prime_instant-master
20:40:30 978.881409 T:1362629536   DEBUG: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.prime_instant-master/default.py): instantiating addon using automatically obtained id of "plugin.video.prime_instant" dependent on version 2.1.0 of the xbmc.python api
20:40:30 978.925964 T:1463292832   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.prime_instant] took 104 ms
20:40:31 979.320251 T:1961218048   DEBUG: ------ Window Init (DialogBusy.xml) ------
20:40:31 979.762756 T:1362629536   DEBUG: https://www.amazon.com
20:40:32 980.738525 T:1961218048   DEBUG: ------ Window Init (DialogKeyboard.xml) ------
20:40:32 980.746155 T:1961210784   DEBUG: CAnnouncementManager - Announcement: OnInputRequested from xbmc
20:40:32 980.746582 T:1961210784   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputRequested
20:40:51 999.593262 T:1961218048   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
20:40:51 999.593567 T:1961210784   DEBUG: CAnnouncementManager - Announcement: OnInputFinished from xbmc
20:40:51 999.593750 T:1961210784   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputFinished
20:40:51 999.808594 T:1961218048   DEBUG: ------ Window Init (DialogKeyboard.xml) ------
20:40:51 999.813660 T:1961210784   DEBUG: CAnnouncementManager - Announcement: OnInputRequested from xbmc
20:40:51 999.813904 T:1961210784   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputRequested
20:41:00 1008.926697 T:1463292832   DEBUG: Thread JobWorker 1463292832 terminating (autodelete)
20:41:35 1043.213745 T:1961218048   DEBUG: OnKey: return (0xf00d) pressed, trying keyboard action 7
20:41:35 1043.214111 T:1961218048   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
20:41:35 1043.550293 T:1961218048   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
20:41:35 1043.550537 T:1961210784   DEBUG: CAnnouncementManager - Announcement: OnInputFinished from xbmc
20:41:35 1043.550781 T:1961210784   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputFinished
20:41:37 1045.677368 T:1362629536   DEBUG: https://www.amazon.com
20:41:38 1047.175293 T:1961218048   DEBUG: Previous line repeats 1 times.
20:41:38 1047.175537 T:1961218048   DEBUG: ------ Window Init (DialogKeyboard.xml) ------
20:41:39 1047.182617 T:1961210784   DEBUG: CAnnouncementManager - Announcement: OnInputRequested from xbmc
20:41:39 1047.182983 T:1961210784   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputRequested
20:41:40 1048.663208 T:1939841952   DEBUG: CAESinkPi:Deinitialize
20:41:40 1048.663818 T:1939841952   DEBUG: CAESinkPi:SetAudioProps hdmi_stream_channels 0 hdmi_channel_map 00000000
20:41:40 1048.676270 T:1939841952   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.audio_render handle 0x6afbd4d0
```

**Comment by liberty-developer** [comment]
Is this issue still alive?
